FROM mcr.microsoft.com/playwright:v1.40.0-jammy

WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier les fichiers de test
COPY . .

# Créer un répertoire pour les résultats des tests
RUN mkdir -p test-results

# Commande pour exécuter les tests
CMD ["npx", "playwright", "test", "--reporter=list,html,junit"]
