const allRoles = {
  user: [
    'getBlogPosts',
    'getFreeBlogPosts',
    'getCategories',
    'updateProfile',
    'getAffiliateStats',
    'getSubscription',
  ],
  subscriber: [
    'getBlogPosts',
    'getFreeBlogPosts',
    'getPremiumBlogPosts',
    'getCategories',
    'updateProfile',
    'getAffiliateStats',
    'getSubscription',
  ],
  affiliate: [
    'getBlogPosts',
    'getFreeBlogPosts',
    'getPremiumBlogPosts',
    'getCategories',
    'updateProfile',
    'getAffiliateStats',
    'manageAffiliateLinks',
    'getSubscription',
    'getAffiliatePayments',
  ],
  editor: [
    'getBlogPosts',
    'getFreeBlogPosts',
    'getPremiumBlogPosts',
    'createBlogPosts',
    'manageBlogPosts',
    'getCategories',
    'manageCategories',
    'updateProfile',
    'getAffiliateStats',
    'getSubscription',
    'getAnalytics',
  ],
  translator: [
    'getBlogPosts',
    'getFreeBlogPosts',
    'getPremiumBlogPosts',
    'manageTranslations',
    'getCategories',
    'updateProfile',
    'getSubscription',
  ],
  admin: [
    'getBlogPosts',
    'getFreeBlogPosts',
    'getPremiumBlogPosts',
    'createBlogPosts',
    'manageBlogPosts',
    'getCategories',
    'manageCategories',
    'getUsers',
    'manageUsers',
    'updateProfile',
    'getAffiliateStats',
    'manageAffiliateLinks',
    'getSubscription',
    'manageSubscriptions',
    'getAffiliatePayments',
    'manageAffiliatePayments',
    'getAnalytics',
    'manageAnalytics',
    'manageTranslations',
    'manageSiteSettings',
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

module.exports = {
  roles,
  roleRights,
};
